-- DragonWave 2026 - Supabase Schema (camelCase version)

-- Racers Table
CREATE TABLE IF NOT EXISTS racers (
    id TEXT PRIMARY KEY,
    bib INTEGER UNIQUE,
    category TEXT,
    distance TEXT,
    isSeries INTEGER DEFAULT 0,
    status TEXT DEFAULT 'registered',
    startTime BIGINT,
    finishTime BIGINT,
    totalTime BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Members Table
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    racerId TEXT REFERENCES racers(id) ON DELETE CASCADE,
    name TEXT,
    birthDate TEXT,
    otprobaId TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Categories (Starts) Table
CREATE TABLE IF NOT EXISTS categories (
    key TEXT PRIMARY KEY,
    startTime BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS (Row Level Security) - initially public for simplicity, but can be hardened
ALTER TABLE racers ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Allow all for now (development policy)
CREATE POLICY "Public Access" ON racers FOR ALL USING (true);
CREATE POLICY "Public Access" ON members FOR ALL USING (true);
CREATE POLICY "Public Access" ON categories FOR ALL USING (true);
