-- DragonWave 2026 - Supabase Schema (snake_case version)
-- Ez a verzió elkerüli a PostgreSQL kis- és nagybetű érzékenységéből adódó hibákat.

-- Táblák törlése az újrakezdéshez (Fejlesztés alatt)
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS racers;
DROP TABLE IF EXISTS categories;

-- Racers Table
CREATE TABLE racers (
    id TEXT PRIMARY KEY,
    bib INTEGER UNIQUE,
    category TEXT,
    distance TEXT,
    is_series INTEGER DEFAULT 0,
    status TEXT DEFAULT 'registered',
    start_time BIGINT,
    finish_time BIGINT,
    total_time BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Members Table
CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    racer_id TEXT REFERENCES racers(id) ON DELETE CASCADE,
    name TEXT,
    birth_date TEXT,
    otproba_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Categories (Starts) Table
CREATE TABLE categories (
    key TEXT PRIMARY KEY,
    start_time BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS
ALTER TABLE racers ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Public Access Policies
CREATE POLICY "Public Access" ON racers FOR ALL USING (true);
CREATE POLICY "Public Access" ON members FOR ALL USING (true);
CREATE POLICY "Public Access" ON categories FOR ALL USING (true);

-- Checkpoints Table
CREATE TABLE IF NOT EXISTS checkpoints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    racer_bib BIGINT NOT NULL,
    checkpoint_name VARCHAR(255) NOT NULL,
    timestamp BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE checkpoints ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON checkpoints FOR ALL USING (true);
